### PR TITLE
Add voices feature

### PR DESCRIPTION
**Pull request by francois-caddet**
The branch should not be merged for now but in progress
Implemented for AVFoundation backend but set_voice has no effect for now
Warning: does not build on Linux or windows for now

### CODE REVIEW

**Comment by ndarilek** [comment]
Is this ready to merge?

I wanted to land utterance start/finish callbacks for 0.7 since those will likely improve performance on mobile, but I'd like to slate this for 0.8 if it's ready.

Are you able to cover all platforms, or do I need to do that?

**Comment by francois-caddet** [comment]
Hello,

Sorry, I was busy those days so I couldn’t work on it.
I can do it for linux this weekend. At least check if it compile and work even if the “voices” feature implementation is not finished.
For Windows… I don’t have any windows machine and Virtualbox is broken since I upgraded macOS to the 11.0beta ;)

**Comment by ndarilek** [comment]
No worries, take your time.


TBH, I don't mind if this takes a while. I'm happy to help you merge it, 
but it isn't a feature I personally need, so things like callbacks have 
priority. I do eventually want to add voices support, but like with all 
other features, I want it to have a nice interface across platforms, 
including listing available voices and getting back a standard trait, 
something like:


```

trait Voice {

     backend: Backend, // Avoid setting one backend to another's voice.

     Name: String,

     language: Option<String>, // Investigate Rust language code libraries

     gender: Option<String>,

...

}

```


So if it takes time to figure that out, that's fine. Also happy to 
collaborate with you on that.


Thanks!

**Comment by francois-caddet** [comment]
> On Sep 25, 2020, at 6:01 PM, Nolan Darilek <notifications@github.com> wrote:
> 
> 
> No worries, take your time.
Thank. It does not start well on linux, I have issues building speech-dispatcher crate. I’ll check this weekend.
> 
> 
> TBH, I don't mind if this takes a while. I'm happy to help you merge it, 
> but it isn't a feature I personally need, so things like callbacks have 
> priority. I do eventually want to add voices support, but like with all 
> other features, I want it to have a nice interface across platforms, 
> including listing available voices and getting back a standard trait, 
> something like:
> 
> 
> ```
> 
> trait Voice {
> 
>     backend: Backend, // Avoid setting one backend to another's voice.
> 
>     Name: String,
> 
>     language: Option<String>, // Investigate Rust language code libraries
> 
>     gender: Option<String>,
> 
> ...
> 
> }

Yes good idea. I can work on that and you merge only when it’s done with a clean api :)
> 
> ```
> 
> 
> So if it takes time to figure that out, that's fine. Also happy to 
> collaborate with you on that.
Me to.
Actually I started to implement the voice feature because I need it for an other project (not already on GitHub…) So I’ll be happy to follow working on.

Also it’s my first rust real project ;) so if you have advices about the code, don’t hesitate.

**Comment by saona-raimundo** [comment]
Hi there! 

Thank you for working on it!

Let me leave my two cents here. On language tag, I saw two options:
- [rust-language-tags](https://crates.io/crates/language-tags)
- [whatlang::Lang](https://docs.rs/whatlang/0.12.0/whatlang/enum.Lang.html)

Since the later implements the [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) standard, and now we have the [IANA registry](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) that [puts al tags in one place](https://www.w3.org/International/articles/language-tags/#registry), I would say that [rust-language-tags](https://crates.io/crates/language-tags) is the way to go :)

**Comment by ndarilek** [comment]
Cool, the Linux speech-dispatcher backend is about to gain support for listing voices. With the ability to implement this on two platforms, I'd like to get it merged. Sorry for how long this has taken.

If you can resolve the conflicts, I'm going to work on the speech-dispatcher PR to get it working there. I'll then merge this PR as a starting point, possibly sometime next week, and iterate on the API until I get something that works everywhere.

Thanks.

**Comment by francois-caddet** [comment]
Ok, conflicts are fixed. It build but examples are not working on my system (macOS 10.15.7).
I will investigate as soon as possible. Sorry for the delay...

**Comment by francois-caddet** [comment]
Also, I didn't check my code since last year ;) A big rework has to be done I suppose.
What is the state of this feature in speech-dispatcher backend?

**Comment by ndarilek** [comment]
Thanks a bunch. This has been open for a while, for which I apologize.

This is now a priority for me and I'm going to try merging it today. It needs some rustfmt work, and I may combine some modules depending on what makes sense to me, but I'll do that work myself.

Thanks again!

**Pull request merged**
