### PR TITLE
Implementing common traits

### LINKED ISSUE #17: Implementing Debug trait and other common traits
Hi there! 

Thank you for the crate!

I wanted to ask if we could implement the `Debug` trait... and other [common traits](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits), as advised by the Rust API guidelines.

I am happy to do some PRs if you want to.

### PR DESCRIPTION
**Pull request by saona-raimundo**
Closes #17

### CODE REVIEW

**Comment by saona-raimundo** [comment]
@ndarilek, may I request another run, please? :)

**Comment by ndarilek** [comment]
Sorry, I thought you were approved already. Approving again.

**Comment by saona-raimundo** [comment]
No worries!

Let me know if it becomes too bothersome to approve the workflow :)

**Comment by saona-raimundo** [comment]
All tests passed! :)

**Comment by ndarilek** [comment]
Thank you!

**Pull request merged**
